services:
  postgres:
    image: postgres:17
    container_name: game-postgres

    restart: unless-stopped

    ports:
      - "55432:5432"

    environment:
      POSTGRES_DB: game
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U game -d game"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
